# Generated by Django 4.2.3 on 2023-07-14 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicants', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=299)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=600)),
                ('description', models.TextField()),
                ('work_place', models.CharField(choices=[('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('Office', 'Office')], max_length=255)),
                ('salary_range', models.CharField(blank=True, max_length=299, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.categories')),
                ('company_published', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_offer', to='company.companyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Considered', 'Considered'), ('No Luck', 'No Luck')], default='Pending', max_length=10, null=True)),
                ('response_message', models.TextField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicants.applicantsprofile')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.job')),
            ],
        ),
    ]
