# Generated by Django 4.2.3 on 2023-07-14 11:44

import django.core.validators
from django.db import migrations, models
import travaii.methods.customize_file_path


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantsProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=travaii.methods.customize_file_path.customize_display_url)),
                ('resume', models.FileField(null=True, upload_to=travaii.methods.customize_file_path.customize_display_url, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'docx'])])),
                ('github', models.URLField(blank=True, null=True, unique=True)),
                ('personal_website', models.URLField(blank=True, null=True, unique=True)),
                ('is_public', models.CharField(choices=[('Anyone', 'Anyone'), ('Only you', 'Only you')], default='Anyone', max_length=20)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
