# Generated by Django 4.2.3 on 2023-07-22 09:32

from django.db import migrations, models
import travaii.methods.customize_file_path


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantsprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/default/imgDefault.png', null=True, upload_to=travaii.methods.customize_file_path.customize_display_url),
        ),
    ]
